version: "3"
services:
  refuge-service:
    build: "./rescateCR"
    depends_on:
      - rescateCR-db
    environment:
      - DATABASE_URL=postgresql://postgres:1234@rescateCR-db:5432/rescateCR
      - APP_SETTINGS=server.config.DevelopmentConfig
    ports:
      - 5000:5000
    volumes:
      - ./rescateCR:/app

  rescateCR-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=rescateCR
    ports:
      - 0.0.0.0:7200:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
